server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   #  mybatis配置文件所在路径
  type-aliases-package: com.zjut.springcloud.entity    #  所有别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml  #  mapper映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: zfm
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001-hystrix #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址


info:
  app.name: microservicecloud
  company.name: www.zjut.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
